### ISSUE TITLE
Latest release Windows version not working

### ISSUE THREAD

**Issue by Pasado80** [Deep-Symmetry/carabiner#10]
Hi,

Thanks for the great software! 

I'm having issues with the Windows version of the latest release (v1.1.0). Previous versions available here run fine, however, the latest version comes up with a "Failed to parse beat time" error message (screenshot attached). 

I've noticed that the file size of the Zip and exe. have dropped considerably since from the previous version also. Maybe the latest build didn't work properly? 

I've had a go at building an executable from the source code myself but I'm encountering problems there also (most likely due to my limited experience with this sort of thing).

Any help is appreciated. Although version 1.0.0 works fine for me so no biggie :)

![Capture](https://user-images.githubusercontent.com/49233076/55471083-4c5a4b80-564c-11e9-9529-30a44035dd94.PNG)

**Comment by brunchboy** [comment]
I have had other people report that this occasionally happens to them as well, but have not been able to explain it yet. (The same build sometimes works fine for hours, and then suddenly gets into this state).

I think the file size got smaller because of a fix to the way it was built to be a production build in Visual Studio, which is smaller, and contains all the proper DLLs to run on non-developer systems.

Unfortunately, I am not even slightly a Windows developer, so I cannot offer any help. If you are able to figure out the problem, a pull request would be greatly appreciated! Adding some debug code to print out the string that is failing to parse would be my first step. I am wondering if there is some issue between floating point formats in Java and the Windows C++ libraries?

**Comment by brunchboy** [comment]
Have you made any progress in investigating this? I would love to understand what is causing this problem for some people.

**Comment by brunchboy** [comment]
I have added a [new preview release](https://github.com/Deep-Symmetry/carabiner/releases/download/v1.1.0/Carabiner_Win_x64_Preview.zip) that prints much more detailed information when it is unable to parse a number. @Pasado80 could you please try this version and report what it says when the problem occurs?

**Comment by brunchboy** [comment]
This is fixed in release 1.1.1. The problem turns out to be that Windows is unlike all other 64-bit operating systems, in that it still uses 32-bit values for `long` integers [(LLP64 model)](https://en.wikipedia.org/wiki/64-bit_computing#64-bit_data_models), while the others follow Java in using 64 bit values for them.

**Comment by Pasado80** [comment]
Sorry. Haven't been back to this thread since posting. I'll give the updated version a go this arvo. Thanks heaps for your work :)

**Comment by brunchboy** [comment]
No worries! Thankfully another person ran into the problem using my improved-errors build, and that enabled me to figure it out. I would appreciate hearing if it seems to have cleared up for you as well. Also, what is an “arvo”? I have never encountered that word before. 😄
