### ISSUE TITLE
Headles pro link to midi clock

### ISSUE THREAD

**Issue by maaraneasi** [Deep-Symmetry/carabiner#14]
Hey!
I have been using the beat-link-trigger up until now because it supports translation of the dj link to midi but it requires carrying an expensive laptop just to act as a translator...
Is there any chance that the link to midi functionality could be ported to carabiner so this simple link->midi clock translation can run on a headless and cheap device? The idea is that we would specify the midi device (usb midi interface), midi start and midi start behavior and the player to watch as startup parameters of the carabiner and all it would do would be syncing a connected midi device same like beat-link-trigger does but without the gui and other stuff we don't need for this use case.
Thanks!
Marek

**Comment by brunchboy** [comment]
I am surprised MIDI clock works for you from BLT, it is not a protocol that is designed to work with general-purpose programming languages and operating systems.

Carabiner is not going to get new functionality. It is as little code as possible to do one very focused thing: bridge the license and language runtime barriers between BLT and Ableton Link. I am not a C++ developer, and even if I were, it would be bad design to overload Carabiner in such a fashion.

However, you can run Beat Link Trigger on an inexpensive Raspberry Pi. It works great, with its full feature set and GUI, on a Raspberry Pi 4 (using the built-in OpenVNC to access the GUI over the network for initial configuration and setup, but after that, current versions of BLT can work without GUI intervention, they go into a “searching” state when disconnected from the DJ Link network, and then automatically reconnect when one appears).

So all you need to do is configure the Pi so that it automatically boots to the OpenVNC desktop, and runs Beat Link Trigger, which will restore its saved configuration and start watching for the DJ Link devices. I have validated that this works well.

**Comment by brunchboy** [comment]
Actually, @maaraneasi during my drive to work I realized I was even more confused about what you were proposing than I thought… what software were you planning to use to connect to the DJ Link network and control Carabiner, and where were you going to run that? Carabiner is not able to communicate with a DJ Link network; Beat Link Trigger does that, and uses Carabiner to relay information to Ableton Link.

What you really want sounds like a Raspberry Pi 4 with a current Beat Link Trigger version installed and running at boot in an OpenVNC headless X Windows GUI environment. You could then plug it in on stage, power it up, connect it to the players and to your MIDI interface, and be in business. If you wanted to get fancy, you could add some triggers to control some of the GPIO pins to drive LEDs that would indicate it had connected to the DJ Link network, and the beats of the master player or the like. 😄
