### ISSUE TITLE
Let Carabiner feed Links master tempo when USB is selected as input source on all four DJM channels

### ISSUE THREAD

**Issue by woorszt** [Deep-Symmetry/carabiner#23]
Hi,

I have read through the documentation but couldn't find any information on this. 

My goal is to let Ableton Link be the master tempo to control a DJM's effect unit BPM in sync and quantized on all four channels but also when USB is selected as the input source. I usually have four tracks in my Ableton set which I feed accordingly to my DJM mixer into channels 1-4. As far as I know, Carabiner can only act as one virtual player and therefore only control the effect units BPM of that particular deck number.  Further, it seems to me that a Pro DJ Link is only engaged when Line or Digital is selected as the input source.

1. Is it possible that Carabiner can act as up to 4 players to send BOM information to DJM Channel 1-4?
2. is it possible that Pro DJ Link can also be used along Carabiner when USB is selected as an input source?

Regards
Christian

**Comment by brunchboy** [comment]
Hello, Christian! Your question seems to reflect many confusions about how Pro DJ Link actually works. I am not sure what documentation you read, but I would encourage you to spend some time studying my [ecosystem analysis](https://djl-analysis.deepsymmetry.org/djl-analysis/packets.html).

In any case, the Carabiner project does not communicate with DJ Link. To do the kinds of things you are trying to accomplish, you should be looking at [Beat Link Trigger](https://github.com/Deep-Symmetry/beat-link-trigger) for a user interface and integration platform, or if you are looking for a Java library to use from your own code, [beat-carabiner](https://github.com/Deep-Symmetry/beat-carabiner) provides the bridge between Carabiner and the [Beat Link](https://github.com/Deep-Symmetry/beat-link) library that communicates with Pro DJ Link (and offers the virtual CDJ). This is what Beat Link Trigger uses.

Carabiner never acts as any players. Beat Link acts as a virtual player. You only need one virtual player to control the tempo of as many players as you like, because you set the virtual player as the master player, and set the other players to sync to it. With the help of beat-carabiner, that master player’s tempo and beat alignment can be controlled from Ableton Link using Carabiner (which is embedded within beat-carabiner).

By far the best way to get a handle on how this all works together is to install Beat Link Trigger, and use its Carabiner window to play around with sync between players and Ableton Link, as described in the [User Guide](https://blt-guide.deepsymmetry.org/beat-link-trigger/7.1.0/Link.html).

What do you mean when you say “USB is chosen as an input source”? In what? DJ Link allows players to sync with each other. The mixer is not involved in that, except in the sense that it can sync to a player as well. Of course you are going to face a limitation from the fact that, prior to the DJM-3000 you can only have up to four players on the network, and to have Ableton LInk controlling the tempo, this means that Beat Link’s virtual player needs to be one of those four, and it needs to be assigned a device number from 1 through 4, so you are only going to be able to have three other CDJs on the network.

So as best I can understand what you are trying to do, you will need to configure Beat Link Trigger to use a real player number for its virtual CDJ, set your mixer to be synced to the virtual CDJ in Beat Link Trigger, which is being driven by Ableton Link, and then tell your mixer’s beat effects to sync to that. I believe that worked fine on my DJM-2000 nexus, but you will need to experiment with how to achieve that on your own mixer. Again, I encourage you to experiment with this using Beat Link Trigger, consulting the user guide section I linked to above.

In any case, this is not an issue with Carabiner (or indeed an issue at all), so GitHub is not the appropriate place to be asking questions like this. I am closing this issue; in the future, if you have general exploratory questions like this, please ask them in the [Zulip community chat](https://deep-symmetry.zulipchat.com/#narrow/stream/275322-beat-link-trigger)
