### ISSUE TITLE
Windows

### ISSUE THREAD

**Issue by kris-audio** [Deep-Symmetry/carabiner#5]
Will a windows version be available? if so when?

**Comment by brunchboy** [comment]
It certainly could be if someone who uses Windows takes the time to build, test, and host it. I would be happy to link to that once it is done. Would you be willing to try? Perhaps you could work with @nonspacial who is trying to figure out how to get the libraries to compile properly, see #4.

**Comment by brunchboy** [comment]
But of course I can’t offer any guesses about when someone might be willing and able to do this.

**Comment by sergioherculano** [comment]
Windows version published just look one of last post of the followingn chat
https://github.com/brunchboy/carabiner/issues/4#issuecomment-384729202

**Comment by brunchboy** [comment]
I saw that posting! If you could share the actual steps that were needed to make it work, and submit a Pull Request containing any changes to this project (as long as they don’t break the Mac build), that would be great! I can’t just host a binary that I can’t build myself, however, because I’d have no way of knowing what was actually in it.

**Comment by brunchboy** [comment]
As noted in #4 I’ve now built a Windows download and added it to the [Releases](https://github.com/brunchboy/carabiner/releases) page.
